### ISSUE TITLE
example thru_client not working (Python 2.7)

### ISSUE THREAD

**Issue by brenzi** [spatialaudio/jackclient-python#26] opened 2015-09-16 19:04 UTC
When I try to run your example script thru_client.py with python2.7 (linux, ubuntu 14.10), I get:

```
$ python thru_client.py 
Press Ctrl+C to stop
From callback <function callback_wrapper at 0xb6f0aa3c>:
Trying to convert the result back to C:
TypeError: an integer is required
```

Any idea what's wrong?

My versions of dependencies:
JACK-Client==0.3.0
cffi==0.8.2

**Comment by mgeier** [comment] 2015-09-17 10:02
I think the problem is that the version of the example you are using is newer than 0.3.0 and incompatible.
In 0.3.0 you had to return a number from the process callback (typically `jack.CALL_AGAIN` or `jack.STOP_CALLING`), this is not necessary anymore in a more recent version.
This is the compatible version of the example: https://github.com/spatialaudio/jackclient-python/blob/0.3.0/examples/thru_client.py

I just created a new release: https://pypi.python.org/pypi/JACK-Client/0.4.0

If you update to 0.4.0, your original example should work again.

**Comment by brenzi** [comment] 2015-09-17 18:29
that works, thanks!

**Comment by mgeier** [comment] 2015-09-19 10:27
Great! I'm closing this issue.

**Closed by mgeier** 2015-09-19 10:27 UTC
